// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfhzvuwxkrmjkfqryvls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmaHp2dXd4a3JtamtmcXJ5dmxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDU5OTcsImV4cCI6MjA2NzgyMTk5N30.H7QkzR606dSkC9udpwwUC0Yq06cUQ4nAKSgC38omc68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});